export const TYPES = {
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
  REGISTER_USER: "REGISTER_USER",
  REGISTER_FAIL: "REGISTER_FAIL",
  AUTH_USER: "AUTH_USER",
  USER_LOADED: "USER_LOADED",
  LOGIN_USER: "LOGIN_USER",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};
